[package]
name = "canja/repo"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
bytenet = "ffrostflame/bytenet@0.4.6"
signal = "sleitnick/signal@2.0.1"